#!/usr/bin/env python3
"""Turn a BDF bitmap font (8 pixels wide, 16 high) into a C array, glyphs 32..126 only.

  python3 tools/bdf2c.py runtime/port/ui/third_party/spleen-8x16.bdf > runtime/port/ui/font.c

The output is const unsigned char settings_font[256][16]: one byte per row, most
significant bit leftmost, every glyph outside 32..126 blank.
"""
import re
import sys

W, H = 8, 16


def parse(path):
    comments, glyphs = [], {}
    box = None
    enc = bbx = None
    rows = None
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line.startswith("COMMENT"):
                comments.append(line[8:].strip())
            elif line.startswith("FONTBOUNDINGBOX"):
                box = [int(v) for v in line.split()[1:5]]
            elif line.startswith("ENCODING"):
                enc = int(line.split()[1])
            elif line.startswith("BBX"):
                bbx = [int(v) for v in line.split()[1:5]]
            elif line == "BITMAP":
                rows = []
            elif line == "ENDCHAR":
                if enc is not None and 32 <= enc <= 126:
                    glyphs[enc] = (bbx, rows)
                enc = bbx = rows = None
            elif rows is not None:
                rows.append(int(line, 16))
    return comments, box, glyphs


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: bdf2c.py FONT.BDF > font.c")
    comments, box, glyphs = parse(sys.argv[1])
    if box[0] != W or box[1] != H:
        sys.exit("bdf2c: the font is %dx%d, not %dx%d" % (box[0], box[1], W, H))
    ascent = box[1] + box[3]
    title = next((c for c in comments if re.match(r"Spleen \S+ \S+$", c)), "Spleen 8x16")
    missing = [c for c in range(32, 127) if c not in glyphs]
    if missing:
        sys.exit("bdf2c: glyphs missing: %s" % missing)
    out = []
    out.append("/* The settings screen's font: %s, generated by tools/bdf2c.py from" % title)
    out.append("   runtime/port/ui/third_party/spleen-8x16.bdf. Copyright (c) 2018-2026 Frederic Cambus,")
    out.append("   BSD 2-Clause licence (runtime/port/ui/third_party/LICENSE). Glyphs 32..126; the rest blank.")
    out.append("   Do not edit: change the BDF or the script and run it again. */")
    out.append("const unsigned char settings_font[256][16] = {")
    for c in range(256):
        cells = [0] * H
        if c in glyphs:
            (w, h, xo, yo), rows = glyphs[c]
            top = ascent - (yo + h)
            for i, r in enumerate(rows):
                if 0 <= top + i < H:
                    cells[top + i] = r if xo == 0 else (r >> xo if xo > 0 else (r << -xo) & 0xFF)
        label = "'%s'" % chr(c) if 32 < c < 127 and chr(c) not in "\\'" else str(c)
        out.append("    /* %s */ {%s}," % (label, ",".join("0x%02X" % b for b in cells)))
    out.append("};")
    print("\n".join(out))


main()
